# Comment that will be sent if an issue is judged to be closed
comment: "Hi there. </br>  
          </br>
          Thank you for filing this issue. Unfortunately, we cannot help you, as you haven't sticked to the provided template and/or have not provided all information requested. Consequently, this issue has been closed.  </br>
          We're more than happy to help out where we can once you raise a new issue containing all requested information in the requested format. </br>
          </br>
          In this regard, please take note that: </br>
          - read the template thoroughly</br>
          - all given header lines (starting with ###) **must not be deleted** </br>
          - everything enclosed by `<!-- -->` is intended to give you guidance and should be replaced by your input specific to the issue </br>
          - Listings regarding your environment must be filled out completely where applicable (bug reports and user questions).</br>
          - Not following the template or providing insufficient information can still implicate manual closure.</br>
          </br>
          So please, first help us a bit to help you! </br>"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the bug"
  - "Steps to reproduce the behavior"
  - "Expected behavior"
  - "Screenshots"
  - "Environment"
  - "deCONZ Logs"
  - "Additional context"
- content:
# Example 2: Device Request
  - "Device"
  - "Screenshots"
- content:
# Example 3: Feature Request
  - "Feature request type"
  - "Description"
  - "Considered alternatives"
  - "Additional context"
- content:
# Example 4: User Question
  - "Describe the question or issue you are having"
  - "Screenshots"
  - "Environment"
  - "deCONZ Logs"
  - "Additional context"
# The issue is judged to be legal if it includes all keywords from any of these configs.
# Or it will be closed by the app.
