#ifndef MFSPECIFIC_CLUSTER_XIAOYAN_H
#define MFSPECIFIC_CLUSTER_XIAOYAN_H

#define XIAOYAN_CLUSTER_ID                 0xFCCC

#define XIAOYAN_ATTRID_ROTATION_ANGLE      0x001B
#define XIAOYAN_ATTRID_DURATION            0x001A

#endif // MFSPECIFIC_CLUSTER_XIAOYAN_H
