#ifndef XIAOMI_H
#define XIAOMI_H

#define XIAOMI_ATTRID_DEVICE_MODE         0x0009
#define XIAOMI_ATTRID_SPECIAL_REPORT      0x00F7
#define XIAOMI_ATTRID_MOTION_SENSITIVITY  0x010C
#define XIAOMI_ATTRID_P1_MOTION_DETECTION 0x0112
#define XIAOMI_ATTRID_MULTICLICK_MODE     0x0125
#define XIAOMI_ATTRID_SPEED               0x0408
#define XIAOMI_ATTRID_CHARGING            0x0409

#endif // XIAOMI_H
